# IF ELSE and ELIF

In [47]:
mark = 90

In [48]:
if mark >= 91 :
    print("Grade -> S")
elif mark >= 81 and mark <91:
    print("Grade-> A")
elif mark >= 71 and mark <81:
    print("Grade-> B")
elif mark >= 61 and mark <71:
    print("Grade-> C")
elif mark >= 57 and mark <61:
    print("Grade-> D")
elif mark >= 50 and mark <57:
    print("Grade-> E")
else:
    print("Grade-> U")

Grade-> A

# For Loop

In [49]:
for x in range(1,1000):
    if x > 1:        
        for y in range(2, x):
            if (x % y == 0) :
                break
        else:
            print(x)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997

In [15]:
for a in range(1,11):
    print(a,"table")
    for b in range(1,11):
        print(b,"X",a,"=",b*a)
    print("")

1 table
1 X 1 = 1
2 X 1 = 2
3 X 1 = 3
4 X 1 = 4
5 X 1 = 5
6 X 1 = 6
7 X 1 = 7
8 X 1 = 8
9 X 1 = 9
10 X 1 = 10

2 table
1 X 2 = 2
2 X 2 = 4
3 X 2 = 6
4 X 2 = 8
5 X 2 = 10
6 X 2 = 12
7 X 2 = 14
8 X 2 = 16
9 X 2 = 18
10 X 2 = 20

3 table
1 X 3 = 3
2 X 3 = 6
3 X 3 = 9
4 X 3 = 12
5 X 3 = 15
6 X 3 = 18
7 X 3 = 21
8 X 3 = 24
9 X 3 = 27
10 X 3 = 30

4 table
1 X 4 = 4
2 X 4 = 8
3 X 4 = 12
4 X 4 = 16
5 X 4 = 20
6 X 4 = 24
7 X 4 = 28
8 X 4 = 32
9 X 4 = 36
10 X 4 = 40

5 table
1 X 5 = 5
2 X 5 = 10
3 X 5 = 15
4 X 5 = 20
5 X 5 = 25
6 X 5 = 30
7 X 5 = 35
8 X 5 = 40
9 X 5 = 45
10 X 5 = 50

6 table
1 X 6 = 6
2 X 6 = 12
3 X 6 = 18
4 X 6 = 24
5 X 6 = 30
6 X 6 = 36
7 X 6 = 42
8 X 6 = 48
9 X 6 = 54
10 X 6 = 60

7 table
1 X 7 = 7
2 X 7 = 14
3 X 7 = 21
4 X 7 = 28
5 X 7 = 35
6 X 7 = 42
7 X 7 = 49
8 X 7 = 56
9 X 7 = 63
10 X 7 = 70

8 table
1 X 8 = 8
2 X 8 = 16
3 X 8 = 24
4 X 8 = 32
5 X 8 = 40
6 X 8 = 48
7 X 8 = 56
8 X 8 = 64
9 X 8 = 72
10 X 8 = 80

9 table
1 X 9 = 9
2 X 9 = 18
3 X 9 = 27
4 X 9 = 36
5 X 9 = 45
6 X 9 = 54
7 X 9 = 63
8 X 9 = 72
9 X 9 = 81
10 X 9 = 90

10 table
1 X 10 = 10
2 X 10 = 20
3 X 10 = 30
4 X 10 = 40
5 X 10 = 50
6 X 10 = 60
7 X 10 = 70
8 X 10 = 80
9 X 10 = 90
10 X 10 = 100

In [18]:
primeinput = int(input("Enter Any Number: "))

Number = 1

print("Prime numbers between", 1, "and", primeinput, "are:")

while(Number <= primeinput):
    count = 0
    i = 2

    while(i <= Number//2):
        if(Number % i == 0):
            count = count + 1
            break
        i = i + 1

    if (count == 0 and Number != 1):
        print(" %d" %Number, end = '  ')
    Number = Number  + 1

Enter Any Number: 1000
Prime numbers between 1 and 1000 are:
 2   3   5   7   11   13   17   19   23   29   31   37   41   43   47   53   59   61   67   71   73   79   83   89   97   101   103   107   109   113   127   131   137   139   149   151   157   163   167   173   179   181   191   193   197   199   211   223   227   229   233   239   241   251   257   263   269   271   277   281   283   293   307   311   313   317   331   337   347   349   353   359   367   373   379   383   389   397   401   409   419   421   431   433   439   443   449   457   461   463   467   479   487   491   499   503   509   521   523   541   547   557   563   569   571   577   587   593   599   601   607   613   617   619   631   641   643   647   653   659   661   673   677   683   691   701   709   719   727   733   739   743   751   757   761   769   773   787   797   809   811   821   823   827   829   839   853   857   859   863   877   881   883   887   907   911   919   929   937   941   947   953   967   971   977   983   991   997